defaults: &defaults
  site:
    name: サイト名
    page_keywords: ページキーワード
    meta:
      ogp:
        app_id: Facebook App ID
        type: article
        image_path: /images/og-image.png

development:
  <<: *defaults
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults