# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 286dbcbbdc326b69e81fc0f8bf76b140a673c18f1bec1659ab3ff5574277ff3de9c999d9d6ecb5465c2c89d197957280b493536160f2041f2ec4c6812dead834

test:
  secret_key_base: 28098f5ccfd58559a690df47eaf32df2a9d3d3585d3d526954c3de557e80591c3085d0e4217a7a83ee264bd058e6ed968b27d7e4c3ed49662e39de5abb7591eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
